### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
And here comes the other Fastlane starter package. Same message: be welcome to my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to built upon it :smiley:

### CODE REVIEW

**Comment by Smooth-E** [comment]
Working on editing the metadata right now to submit along this pull request. I am just curious how you managed to make corners of images not rounded?

I am also planning to redraw imagery to be vertical, so here is the question. Should screenshots and other imagery be so compressed? Is there a technical or an ethical (e.g. to not spend too much user's traffic) size limit?

**Comment by IzzySoft** [comment]
> how you managed to make corners of images not rounded?

JPEG has no transparency. So had I left them rounded, they'd looked a bit ugly :wink:

> Should screenshots and other imagery be so compressed? Is there a technical or an ethical (e.g. to not spend too much user's traffic) size limit?

My framework takes care for compression – so feel free to replace the graphics with bigger ones to e.g. be used in other places (like the Readme) as well. And yes, the idea is to reduce traffic and storage size – not only having users with limited data plans on bad connections and with low-end devices in mind, but also the environment. So when updating from Fastlane, my framework resizes screenshots to 350px width (portrait) and converts them to JPG.

**Comment by Smooth-E** [comment]
I had updated the metadata. I would appreciate if you review these changes and confirm that everything is fine before I merge the pull request.

Also, is it appropriate to name Russian locale *ru-RU* and not just *ru*? Will the *ru* metadata be shown to users with *ru-BY* locale for example?

**Comment by IzzySoft** [comment]
> is it appropriate to name Russian locale ru-RU and not just ru? Will the ru metadata be shown to users with ru-BY locale for example?

To my understanding: `ru` would be shown to `ru*`. `ru-RU` would be shown to `ru-RU`. Which is why I'd recommend to stay with `ru`. Just for Playstore you'll need the "full name" – and for `en-US` as that's used as fallback for everything that's missing in another locale.

> I would appreciate if you review these changes

On it:

* structure looks fine (but see above for locale namings)
* changelogs must be plain ASCII (no HTML allowed)
* no need to duplicate the graphics for all locales if they're identical. e.g. if all screenshots are English, just keep them in `en-US` and put none into `ru*`, so a `ru*` visitor would get them from `en-US` (see "fallback" above). Same for icon and featureGraphic (just noticed where the screenshots differ, so those are OK – but icon and featureGraphic don't).

Thanks!

**Comment by Smooth-E** [comment]
Fixed. Merging the changes now.

**Comment by IzzySoft** [comment]
Wonderful, thanks! I've adjusted the config on my end accordingly so it's pulled along with future releases – and triggered a manual pull basically just in the last minute (update checker just started, so sync will happen any minute now). As a result, new screenshots etc. should go live within half an hour :smiley:

**Comment by Smooth-E** [comment]
Hey, @IzzySoft! The new release is now out and I have added some new pictures. Please, add them to your store config so they are displayed on the app page.

**Comment by IzzySoft** [comment]
As I wrote: they'll be pulled along with future releases. This is the first "future release", but missed today's update check by roughly 4 hours, so it will come along with the next one. But "especially for you my friend" I play "on the bazar", and manually triggered an update to make sure it works:

```
$ iod repo get com.smoothie.wirelessDebuggingSwitch
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/releases'
com.smoothie.wirelessDebuggingSwitch: checking tag 'v1.1'
com.smoothie.wirelessDebuggingSwitch: lastRelNo set to '1.1', checking for files
com.smoothie.wirelessDebuggingSwitch: Upstream file date (2023-11-10 22:09) is newer than ours (2023-04-19 22:20).
com.smoothie.wirelessDebuggingSwitch: returning ['1.1','https://github.com/Smooth-E/wireless-adb-switch/releases/download/v1.1/wadbs-v1.1.apk',1699650575]
com.smoothie.wirelessDebuggingSwitch: 1.0/1.1, https://github.com/Smooth-E/wireless-adb-switch/releases: https://github.com/Smooth-E/wireless-adb-switch/releases/download/v1.1/wadbs-v1.1.apk
- Grabbing update for com.smoothie.wirelessDebuggingSwitch: OK
- Checking 'repo/com.smoothie.wirelessDebuggingSwitch_2.apk' for libraries and malware …
com.smoothie.wirelessDebuggingSwitch: check if repo contains FUNDING.yml
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/contents/.github'
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/contents/'
com.smoothie.wirelessDebuggingSwitch: no FUNDING.yml detected.
com.smoothie.wirelessDebuggingSwitch: calling 'getFastlaneMeta(github,[host:github.com,owner:Smooth-E,repo:wireless-adb-switch,path:/fastlane/metadata/android])'
com.smoothie.wirelessDebuggingSwitch: FastlaneFeatures shortdesc,fulldesc,changelogs,icon,featureGraphicJPG,screenshotsJPG
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/contents/fastlane%2Fmetadata%2Fandroid'
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US'
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fchangelogs'
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages'
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages%2FphoneScreenshots'
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/contents/fastlane%2Fmetadata%2Fandroid%2Fru'
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/contents/fastlane%2Fmetadata%2Fandroid%2Fru%2Fchangelogs'
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/contents/fastlane%2Fmetadata%2Fandroid%2Fru%2Fimages'
com.smoothie.wirelessDebuggingSwitch: looking for 'https://api.github.com/repos/Smooth-E/wireless-adb-switch/contents/fastlane%2Fmetadata%2Fandroid%2Fru%2Fimages%2FphoneScreenshots'
com.smoothie.wirelessDebuggingSwitch: checking locale 'en-US'
com.smoothie.wirelessDebuggingSwitch: updating 'metadata/com.smoothie.wirelessDebuggingSwitch/en-US/changelogs/2.txt' from '2.txt'
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/en-US/featureGraphic.jpg' from 'featureGraphic.png'
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/en-US/phoneScreenshots/01.png' as JPG
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/en-US/phoneScreenshots/02.png' as JPG
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/en-US/phoneScreenshots/03.png' as JPG
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/en-US/phoneScreenshots/04.png' as JPG
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/en-US/phoneScreenshots/05.png' as JPG
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/en-US/phoneScreenshots/06.png' as JPG
com.smoothie.wirelessDebuggingSwitch: cross-checking for obsolete screenshots
com.smoothie.wirelessDebuggingSwitch: screenshots in Fastlane: 01,02,03,04,05,06
com.smoothie.wirelessDebuggingSwitch: local screenshots checked: 01,02,03,04,05,06
com.smoothie.wirelessDebuggingSwitch: checking locale 'ru'
com.smoothie.wirelessDebuggingSwitch: updating 'metadata/com.smoothie.wirelessDebuggingSwitch/ru/full_description.txt'
com.smoothie.wirelessDebuggingSwitch: updating 'metadata/com.smoothie.wirelessDebuggingSwitch/ru/changelogs/2.txt' from '2.txt'
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/ru/phoneScreenshots/01.png' as JPG
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/ru/phoneScreenshots/02.png' as JPG
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/ru/phoneScreenshots/03.png' as JPG
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/ru/phoneScreenshots/04.png' as JPG
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/ru/phoneScreenshots/05.png' as JPG
com.smoothie.wirelessDebuggingSwitch: updating 'repo/com.smoothie.wirelessDebuggingSwitch/ru/phoneScreenshots/06.png' as JPG
com.smoothie.wirelessDebuggingSwitch: cross-checking for obsolete screenshots
com.smoothie.wirelessDebuggingSwitch: screenshots in Fastlane: 01,02,03,04,05,06
com.smoothie.wirelessDebuggingSwitch: local screenshots checked: 01,02,03,04,05,06
```

You see, it DOES work :smiley: Result (as seen by a browser set to DE locale):

image

**Comment by Smooth-E** [comment]
Lovely. Thanks!

**Pull request merged**
