### PR TITLE
[zh-CN] add zh-CN

### PR DESCRIPTION
**Pull request by Jesse205**
# Description

# Imagery translation

| Original text        | Translation |
| -------------------- | ----------- |
| Quick Settings Tile  |   快速设置磁贴          |
| Home Screen Widgets  |      主屏幕小部件       |
| Widget Customization |     自定义小部件        |
| Instant Connection   |      即时连接       |

# Rules and agreements

- [x] My commit messages comply with [Conventional commits](https://www.conventionalcommits.org/) (use your IDE's Git manager to edit the commit messages if they don't)
- [x] Original sources of code and imagery (if any) are properly credited
- [x] I agree to keep the discussion under this pull request polite and on point

- [x] I have read [translate.md](translate.md) and this pull request complies with it
- [x] This pull request does not translate [license.md](license.md) and [translate.md](translate.md)
- [x] My translations are of good quality and does not contain inappropriate content

### CODE REVIEW

**Comment by Smooth-E** [comment]
Thanks for translating! I will compose the imagery and submit it here for your review, just to make that the text is properly positioned. Also, since you did not use the flag emoji (is it possible to use one?) I will probably refactor the readme a bit. Afterwards I will merge those new strings and create a minor release for F-Droid. You can expect this all to happen in a week or two.

**Comment by Jesse205** [comment]
emoji:🇨🇳

**Comment by Smooth-E** [comment]
Please, provide translations for all the imagery. You missed "OneUI Integration" and "Root or Shizuku". I would like metadata to be consistent among all the languages the app supports. Please, also provide translations for [store page metadata](https://github.com/Smooth-E/wireless-adb-switch/tree/main/fastlane/metadata/android) (app description and the name, if translatable). It would be also nice if you translate the [documentation on setting up instant connection](https://github.com/Smooth-E/wireless-adb-switch/tree/main/scripts).

If you are familiar with working in Figma, I can share the project file so you can place the text on imagery yourself (as you know better where to split lines or maybe is it correct to position text vertically).

**Comment by Smooth-E** [comment]
Hey, @Jesse205! I released the new version of WADBS with new features (some requested by other users). If you are interested, you can translate the newly added strings and also some imagery that you've missed before. Hope you are doing well!

**Pull request closed without merging**
